package fptu.exe202.signify.signifybe.features.email.application;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.MailException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.Context;

/**
 * Core email sending service.
 * <p>
 * All public methods are {@code @Async} to avoid blocking the HTTP request thread
 * while waiting for SMTP delivery. Because they return {@code void}, any exception
 * thrown after the proxy dispatches the call will <b>not</b> propagate back to the
 * HTTP caller — errors are logged server-side instead.
 * </p>
 * <p>
 * HTML content is rendered via Thymeleaf templates stored under
 * {@code src/main/resources/templates/email/}.
 * </p>
 */
@Service
@RequiredArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
@Slf4j
public class EmailService {

    static final int OTP_EXPIRY_MINUTES = 5;

    final JavaMailSender mailSender;
    final TemplateEngine templateEngine;

    @Value("${spring.mail.username}")
    String fromEmail;

    /**
     * Sends an OTP verification email with branded HTML layout.
     *
     * @param to  recipient address
     * @param otp the 6-digit OTP (generated by the calling service, not here)
     */
    @Async
    public void sendOtpEmail(String to, String otp) {
        Context ctx = new Context();
        ctx.setVariable("otp", otp);
        ctx.setVariable("expiryMinutes", OTP_EXPIRY_MINUTES);

        String html = templateEngine.process("email/otp", ctx);
        doSend(to, "Signify - Your OTP Code", html, "OTP");
    }

    /**
     * Sends a password-reset OTP email with branded HTML layout.
     *
     * @param to  recipient address
     * @param otp the 6-digit OTP (generated by the calling service, not here)
     */
    @Async
    public void sendPasswordResetEmail(String to, String otp) {
        Context ctx = new Context();
        ctx.setVariable("otp", otp);
        ctx.setVariable("expiryMinutes", OTP_EXPIRY_MINUTES);

        String html = templateEngine.process("email/password-reset", ctx);
        doSend(to, "Signify - Password Reset OTP", html, "password-reset");
    }

    /**
     * Sends an arbitrary HTML email.
     *
     * @param to       recipient address
     * @param subject  email subject
     * @param htmlBody pre-rendered HTML content
     */
    @Async
    public void sendHtmlEmail(String to, String subject, String htmlBody) {
        doSend(to, subject, htmlBody, "custom");
    }

    // ── private helpers ─────────────────────────────────────────────────────────

    /**
     * Shared method that builds a {@link MimeMessage}, sends it, and handles errors.
     * <p>
     * Because callers are {@code @Async void}, exceptions are <b>not</b> re-thrown
     * as HTTP errors. They are logged so ops/monitoring can detect SMTP issues.
     *
     * @param to       recipient address
     * @param subject  email subject line
     * @param html     HTML body content
     * @param emailType short label used in log messages (e.g. "OTP", "password-reset")
     */
    private void doSend(String to, String subject, String html, String emailType) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            // multipart=false: we only send HTML text, no inline images or attachments.
            MimeMessageHelper helper = new MimeMessageHelper(message, false, "UTF-8");
            helper.setTo(to);
            helper.setFrom(fromEmail);
            helper.setSubject(subject);
            helper.setText(html, true);

            mailSender.send(message);
            log.info("Email sent [type={}]", emailType);
        } catch (MessagingException | MailException e) {
            log.error("Failed to send email [type={}]", emailType, e);
            // Do NOT re-throw: this runs on the async thread pool.
            // The HTTP response has already been returned to the client.
        }
    }
}
